###get request
GET http://localhost:3000/reporterinfo

# ### post request
# POST http://localhost:3000/reporterinfo
# Content-Type: application/json

# {
#     "rname": "Arpit Chandak",
#     "rnum": "+919079153127",
#     "r_androidid": "safdgsdgf",
#     "r_loc_lat": "65456165",
#     "r_loc_lon": "1564651",
#     "r_device": "dDDf",
#     "r_carrier": "dszf",
#     "r_network": "sdf"
# }

# ###single id get request
# GET http://localhost:3000/data/5ea92f29a0428b29b466dd3c

# ###single id Update request
# PATCH  http://localhost:3000/data/5ea9307c5e6e612408b423eas2
# Content-Type: application/json

# {
#     "avatar": "sadad"
# }

# ###single id delete request
# DELETE  http://localhost:3000/data/5ea92f29a0428b29b466dd3a

# ###single id get request
# GET http://localhost:3000/ 